# Generated by Django 3.2.20 on 2023-10-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ContactInquiries',
        ),
        migrations.AlterModelOptions(
            name='contactinquiries',
            options={'verbose_name_plural': 'Contact Inquiries'},
        ),
    ]
