# Generated by Django 3.2.20 on 2023-10-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_rename_review_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testimonial',
            field=models.TextField(max_length=100),
        ),
    ]
